[versions]
versionCode = "62"
versionName = "Titanium yellow"

# https://mvnrepository.com/artifact/androidx.browser/browser
androidxBrowserBrowser = "1.9.0"
# https://developer.android.com/reference/tools/gradle-api
androidGradlePlugin = "8.12.3"
# https://mvnrepository.com/artifact/androidx.activity/activity-compose
androidxActivityActivityCompose = "1.12.0"
# https://mvnrepository.com/artifact/androidx.appcompat/appcompat
androidxAppCompatAppCompat = "1.7.1"
# https://developer.android.com/jetpack/androidx/releases/compose
androidxCompose = "1.9.5"
# https://developer.android.com/jetpack/androidx/releases/compose
androidxComposeCompiler = "1.5.15"
# https://mvnrepository.com/artifact/androidx.core/core-ktx
androidxCoreCoreKts = "1.17.0"
# https://mvnrepository.com/artifact/androidx.glance/glance-appwidget
androidxGlanceGlance = "1.1.1"
# https://developer.android.com/jetpack/androidx/releases/datastore
androidxDatastoreDatastorePreferences = "1.2.0"
# https://github.com/InsertKoinIO/koin/releases
koin = "4.2.0-alpha2"
# https://mvnrepository.com/artifact/androidx.lifecycle/lifecycle-runtime-compose
androidxLifecycleLifecycleRuntimeCompose = "2.10.0"
# https://developer.android.com/jetpack/androidx/releases/room
androidxRoom = "2.8.4"
# https://mvnrepository.com/artifact/androidx.test/core
androidxTest = "1.7.0"
# https://mvnrepository.com/artifact/androidx.test.ext/junit-ktx
androidxTestExtJunitKtx = "1.3.0"
# https://mvnrepository.com/artifact/androidx.test/runner
androidxTestRunner = "1.7.0"
# https://mvnrepository.com/artifact/androidx.work/work-runtime-ktx
androidxWorkWorkRuntimeKtx = "2.11.0"
# https://mvnrepository.com/artifact/com.android.tools/desugar_jdk_libs
comAndroidToolsDesugarJdkLibs = "2.1.5"
# https://github.com/ktorio/ktor/releases
ktor = "3.3.2"
junitJunit = "4.13.2"
# https://kotlinlang.org/docs/releases.html#release-details
kotlin = "2.2.21"
# https://github.com/google/ksp/releases
ksp = "2.3.2"
# https://github.com/Calvin-LL/Reorderable/releases
reorderable = "3.0.0"
# https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-coroutines-test
kotlinxCoroutines = "1.10.2"
# https://github.com/robolectric/robolectric/releases
orgRobolectricRobolectric = "4.16"
# https://github.com/Kotlin/kotlinx.serialization/releases
kotlinx-serialization = "1.9.0"
# https://github.com/eobermuhlner/big-math/releases
bigMath = "2.3.2"
# https://github.com/iurysza/module-graph/releases
devIurysouzaModulegraph = "0.13.0"
# https://github.com/detekt/detekt/releases
detekt = "1.23.8"
# https://github.com/jordond/MaterialKolor/releases
materialKolor = "5.0.0-alpha03"
# https://github.com/JetBrains/compose-multiplatform/releases
composeMultiplatform = "1.10.0-beta02"
# https://github.com/JetBrains/compose-multiplatform/releases
# https://mvnrepository.com/artifact/org.jetbrains.compose.material3/material3
composeMultiplatformMaterial3 = "1.10.0-alpha05"
# https://github.com/touchlab/Kermit/releases
kermit = "2.0.8"
# https://developer.android.com/jetpack/androidx/releases/annotation
annotation = "1.9.1"
# https://mvnrepository.com/artifact/org.jetbrains.androidx.lifecycle/lifecycle-viewmodel-savedstate
lifecyclyViewModel = "2.10.0-alpha05"
# https://github.com/Kotlin/kotlinx-datetime/releases/latest
kotlinxDatetime = "0.7.1"
navigation3Runtime = "1.0.0-rc01"
navigation3UI = "1.0.0-alpha05"
# https://github.com/eygraber/uri-kmp/releases
uriKmp = "0.0.21"
buildKonfig = "0.17.1"

[libraries]
androidx-activity-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivityActivityCompose" }
androidx-appcompat-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppCompatAppCompat" }
androidx-browser-browser = { module = "androidx.browser:browser", version.ref = "androidxBrowserBrowser" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidxCompose" }
androidx-core-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCoreCoreKts" }
androidx-glance-glance = { module = "androidx.glance:glance", version.ref = "androidxGlanceGlance" }
androidx-glance-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "androidxGlanceGlance" }
androidx-glance-glance-appwidget-preview = { module = "androidx.glance:glance-appwidget-preview", version.ref = "androidxGlanceGlance" }
androidx-glance-glance-preview = { module = "androidx.glance:glance-preview", version.ref = "androidxGlanceGlance" }
androidx-glance-glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "androidxGlanceGlance" }
androidx-datastore-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidxDatastoreDatastorePreferences" }
io-insert-koin-koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
io-insert-koin-koin-core = { module = "io.insert-koin:koin-core" }
io-insert-koin-koin-android = { module = "io.insert-koin:koin-android" }
io-insert-koin-koin-core-coroutines = { module = "io.insert-koin:koin-core-coroutines" }
io-insert-koin-koin-compose = { module = "io.insert-koin:koin-compose" }
io-insert-koin-koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }
io-insert-koin-koin-androidx-startup = { module = "io.insert-koin:koin-androidx-startup" }
io-insert-koin-koin-compose-navigation3 = { module = "io.insert-koin:koin-compose-navigation3" }
androidx-lifecycle-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidxLifecycleLifecycleRuntimeCompose" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidxRoom" }
androidx-room-common = { module = "androidx.room:room-common", version.ref = "androidxRoom" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidxRoom" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidxRoom" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTest" }
androidx-test-ext-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidxTestExtJunitKtx" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTestRunner" }
androidx-work-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "androidxWorkWorkRuntimeKtx" }
big-math = { module = "ch.obermuhlner:big-math", version.ref = "bigMath" }
com-android-tools-desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "comAndroidToolsDesugarJdkLibs" }
io-ktor-ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
io-ktor-ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
io-ktor-ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
io-ktor-ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
io-ktor-ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
junit-junit = { module = "junit:junit", version.ref = "junitJunit" }
sh-calvin-reorderable-reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }
org-robolectric-robolectric = { module = "org.robolectric:robolectric", version.ref = "orgRobolectricRobolectric" }
org-jetbrains-kotlinx-kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
com-materialkolor-material-color-utilities = { module = "com.materialkolor:material-color-utilities", version.ref = "materialKolor" }
org-jetbrains-kotlinx-kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
org-jetbrains-kotlinx-kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
org-jetbrains-kotlin-kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
co-touchlab-kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
androidx-annotation-annotation-jvm = { module = "androidx.annotation:annotation-jvm", version.ref = "annotation" }
org-jetbrains-compose-foundation-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform" }
org-jetbrains-compose-ui-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }
org-jetbrains-compose-runtime-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMultiplatform" }
org-jetbrains-compose-components-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "composeMultiplatform" }
org-jetbrains-compose-ui-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "composeMultiplatform" }
org-jetbrains-compose-ui-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform" }
org-jetbrains-compose-material3-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "composeMultiplatformMaterial3" }
org-jetbrains-compose-material3-material3-window-size = { module = "org.jetbrains.compose.material3:material3-window-size-class", version.ref = "composeMultiplatformMaterial3" }
org-jetbrains-kotlinx-kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
androidx-navigation3-navigation3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "navigation3Runtime" }
org-jetbrains-androidx-navigation3-navigation3-ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "navigation3UI" }
org-jetbrains-androidx-lifecycle-lifecycle-viewmodel-savedstate = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecyclyViewModel" }
org-jetbrains-androidx-lifecycle-lifecycle-viewmodel-navigation3 = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "lifecyclyViewModel" }
com-eygraber-uri-kmp = { module = "com.eygraber:uri-kmp", version.ref = "uriKmp" }

# build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

[plugins]
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "androidxRoom" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dev-iurysouza-modulegraph = { id = "dev.iurysouza.modulegraph", version.ref = "devIurysouzaModulegraph" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
compose = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
com-codingfeline-buildkonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildKonfig" }