[versions]
versionCode = "45"
versionName = "Quick Silver"

# https://mvnrepository.com/artifact/androidx.browser/browser
androidxBrowserBrowser = "1.8.0"
# https://developer.android.com/reference/tools/gradle-api
androidGradlePlugin = "8.7.3"
# https://mvnrepository.com/artifact/androidx.activity/activity-compose
androidxActivityActivityCompose = "1.10.0-rc01"
# https://mvnrepository.com/artifact/androidx.appcompat/appcompat
androidxAppCompatAppCompat = "1.7.0"
# https://developer.android.com/jetpack/androidx/releases/compose
androidxCompose = "1.8.0-alpha07"
# https://developer.android.com/jetpack/androidx/releases/compose
androidxComposeCompiler = "1.5.15"
# https://developer.android.com/jetpack/androidx/releases/compose
androidxComposeMaterial3 = "1.4.0-alpha05"
# https://mvnrepository.com/artifact/androidx.core/core-ktx
androidxCoreCoreKts = "1.15.0"
# https://mvnrepository.com/artifact/androidx.glance/glance-appwidget
androidxGlanceGlance = "1.1.1"
# https://mvnrepository.com/artifact/androidx.datastore/datastore-preferences
androidxDatastoreDatastorePreferences = "1.1.1"
# https://mvnrepository.com/artifact/androidx.hilt/hilt-navigation-compose
androidxHiltHiltNavigationCompose = "1.2.0"
# https://mvnrepository.com/artifact/androidx.lifecycle/lifecycle-runtime-compose
androidxLifecycleLifecycleRuntimeCompose = "2.8.7"
# https://developer.android.com/jetpack/androidx/releases/navigation
androidxNavigationNavigationCompose = "2.8.5"
# https://mvnrepository.com/artifact/androidx.room/room-runtime
androidxRoom = "2.6.1"
# https://mvnrepository.com/artifact/androidx.test/core
androidxTest = "1.6.1"
# https://mvnrepository.com/artifact/androidx.test.ext/junit-ktx
androidxTestExtJunitKtx = "1.2.1"
# https://mvnrepository.com/artifact/androidx.test/runner
androidxTestRunner = "1.6.2"
# https://mvnrepository.com/artifact/androidx.work/work-runtime-ktx
androidxWorkWorkRuntimeKtx = "2.10.0"
# https://mvnrepository.com/artifact/com.android.tools/desugar_jdk_libs
comAndroidToolsDesugarJdkLibs = "2.1.3"
# https://mvnrepository.com/artifact/com.google.dagger/dagger
comGoogleDagger = "2.53.1"
# https://mvnrepository.com/artifact/com.squareup.moshi/moshi-kotlin
comSquareupMoshiMoshiKotlin = "1.15.2"
# https://mvnrepository.com/artifact/com.squareup.retrofit2/converter-moshi
comSquareupRetrofit2ConverterMoshi = "2.11.0"
junitJunit = "4.13.2"
# https://kotlinlang.org/docs/releases.html#release-details
kotlin = "2.1.0"
# https://github.com/google/ksp/releases
ksp = "2.1.0-1.0.29"
# https://github.com/Calvin-LL/Reorderable/releases
reorderable = "2.4.2"
# https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-coroutines-test
orgJetbrainsKotlinxKotlinxCoroutinesTest = "1.9.0"
# https://github.com/robolectric/robolectric/releases
orgRobolectricRobolectric = "4.14.1"
# https://github.com/Kyant0/m3color/releases
comGithubKyant0m3color = "2024.5"
# https://github.com/Kotlin/kotlinx.serialization/releases
kotlinx-serialization = "1.7.2"
# https://github.com/eobermuhlner/big-math/releases
bigMath = "2.3.2"
# https://github.com/iurysza/module-graph/releases
devIurysouzaModulegraph = "0.10.1"
# https://github.com/detekt/detekt/releases
detekt = "1.23.7"

[libraries]
androidx-activity-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivityActivityCompose" }
androidx-appcompat-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppCompatAppCompat" }
androidx-browser-browser = { module = "androidx.browser:browser", version.ref = "androidxBrowserBrowser" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidxComposeMaterial3" }
androidx-compose-foundation-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidxCompose" }
androidx-compose-ui-ui = { module = "androidx.compose.ui:ui", version.ref = "androidxCompose" }
androidx-compose-material3-window-size = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "androidxComposeMaterial3" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidxCompose" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidxCompose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidxCompose" }
androidx-core-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCoreCoreKts" }
androidx-glance-glance = { module = "androidx.glance:glance", version.ref = "androidxGlanceGlance" }
androidx-glance-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "androidxGlanceGlance" }
androidx-glance-glance-appwidget-preview = { module = "androidx.glance:glance-appwidget-preview", version.ref = "androidxGlanceGlance" }
androidx-glance-glance-preview = { module = "androidx.glance:glance-preview", version.ref = "androidxGlanceGlance" }
androidx-glance-glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "androidxGlanceGlance" }
androidx-datastore-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidxDatastoreDatastorePreferences" }
androidx-hilt-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "androidxHiltHiltNavigationCompose" }
androidx-lifecycle-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidxLifecycleLifecycleRuntimeCompose" }
androidx-navigation-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidxNavigationNavigationCompose" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidxRoom" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidxRoom" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidxRoom" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTest" }
androidx-test-ext-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidxTestExtJunitKtx" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidxTestRunner" }
androidx-work-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "androidxWorkWorkRuntimeKtx" }
big-math = { module = "ch.obermuhlner:big-math", version.ref = "bigMath" }
com-android-tools-desugar-jdk-libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "comAndroidToolsDesugarJdkLibs" }
com-google-dagger-android-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "comGoogleDagger" }
com-google-dagger-dagger-android-processor = { module = "com.google.dagger:dagger-android-processor", version.ref = "comGoogleDagger" }
com-google-dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "comGoogleDagger" }
com-squareup-moshi-moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "comSquareupMoshiMoshiKotlin" }
com-squareup-retrofit2-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "comSquareupRetrofit2ConverterMoshi" }
junit-junit = { module = "junit:junit", version.ref = "junitJunit" }
sh-calvin-reorderable-reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }
org-jetbrains-kotlinx-kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "orgJetbrainsKotlinxKotlinxCoroutinesTest" }
org-robolectric-robolectric = { module = "org.robolectric:robolectric", version.ref = "orgRobolectricRobolectric" }
com-github-kyant0-m3color = { module = "com.github.Kyant0:m3color", version.ref = "comGithubKyant0m3color" }
org-jetbrains-kotlinx-kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

[plugins]
android-gradlePlugin = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "comGoogleDagger" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "androidxRoom" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
dev-iurysouza-modulegraph = { id = "dev.iurysouza.modulegraph", version.ref = "devIurysouzaModulegraph" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
